### ISSUE TITLE
When you die have a button that toggles auto spawning and have a spawn button.  Edit your kit while you're dead so you don't get shot while.

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#12]

**Comment by michaeljcalkins** [comment]
![rangersteve_io](https://cloud.githubusercontent.com/assets/8272012/19357502/cff7a8ae-9126-11e6-880a-12f8f5f58f5e.png)

**Comment by And-re** [comment]
We should do this. It will make people aware about possibility to change weapons and prevent easy kills on players changing weapons or that need to take a break and don't want to be forced to respawn.

**Comment by michaeljcalkins** [comment]
@And-re You think this will would be good enough to replace the "self kill" idea?  I don't think we'd need it if we do this.

**Comment by And-re** [comment]
Self kill is useful in other scenarios:
1. you can quickly switch weapons instead of reloading the game (in development mode when you want to test something or you are alone on the server or it's a closed map where you can't kill yourself)
2. you can respawn faster if you are falling down and you're going to die anyway

**Comment by michaeljcalkins** [comment]
![screen_shot_2016-11-02_at_20_19_06](https://cloud.githubusercontent.com/assets/8272012/19974960/85cf4796-a1a7-11e6-9a19-950b1a3c4a5a.png)
![screen_shot_2016-11-02_at_20_19_06 1](https://cloud.githubusercontent.com/assets/8272012/19974975/911e9778-a1a7-11e6-9409-5cfa54ccd486.png)
